### ISSUE TITLE
Vercel にも対応して欲しいです

### ISSUE THREAD

**Issue by hirasawa** [redamoon/mt-plugin-NetlifyBuildHooks#9]
MTをヘッドレスで使うのに非常に便利なプラグインだと思いますので、ぜひ活用の幅を広げるためにもVercel にも対応して頂けると嬉しいです。

**Comment by redamoon** [comment]
@hirasawa 

ご返信遅れてすみません！
現在、こちらでVercel用のプラグインも開発中でした。
https://github.com/redamoon/mt-plugin-VercelDeployHooks

ベースはNelifyのもの延長ではありますが、記事の公開時にビルドが動くようにも対応しておりました。
現在はプレビューでVercelのホスティング且つNext.jsのプレビューモードが表示するような設計と実装をしておりました。
また、記事のみ対応のためコンテンツタイプ用にも追加機能を盛り込みたいと思っています。

**Comment by hirasawa** [comment]
@redamoon 
ご丁寧にありがとうございます！
既に開発中だったんですね、それは嬉しい情報です！！

記事公開時にビルドが動くのも1操作減るので嬉しいですね。

MTをヘッドレスCMSとして使うってあまり需要があるとも思えませんが、ずっとMT使ってきた身としては活用の幅が広がるのは嬉しいので、無理のない程度に頑張ってくださいませ。

**Comment by redamoon** [comment]
@hirasawa 
ご返信ありがとうございます！はい。現在記事だけではありますがそのような感じで対応進めておりました。
またVercel + Next.js ロックインではありますがプレビューのほうも開発してました。
https://github.com/redamoon/mt-plugin-VercelDeployHooks/pull/6

MTをHeadlessで使う需要はたぶんあまりないと思ってたりしていますが、元々Data APIを使うという方針はMT6からあったので活用方法としてはありかなと思い開発しておりました。
まだ調整段階な部分ではありますが、リリースしましたらぜひ使ってみていただけると嬉しいです。
